version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./plots:/usr/src/app/plots
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: