version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./plots:/usr/src/app/plots
    depends_on:
      - db
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_BASE_URL: ${WEATHER_BASE_URL}
      USER_BASE_URL: ${USER_BASE_URL}

  db:
    image: postgres
    environment:
      POSTGRES_DB: salesdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Moudgil1982#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: